# Generated by Django 4.1.3 on 2023-01-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cattle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entrance_data", models.DateField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now_add=True)),
                ("weight", models.IntegerField()),
            ],
        ),
    ]
