# Generated by Django 3.2.5 on 2023-01-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_stable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stable',
            old_name='cattle_id',
            new_name='cattle',
        ),
    ]
